Repository penguineer/ansible-role-flipper_zero_desktop, pull requests merged in 2022-07, with the labels that each got.

#1 Add the initial ansible role
  README.md
  defaults/main.yml
  files/flipperzero.rules
  handlers/main.yml
  meta/main.yml
  tasks/main.yml
Labels: enhancement

#4 Remove left-over debug statement
  tasks/main.yml
Labels: bug

#6 Rename the role to flipper_zero_desktop
  README.md
  meta/main.yml
Labels: enhancement, breaking

#8 Cleanup docs
  README.md
  tasks/main.yml
Labels: documentation

#9 Use checksum to verify and avoid duplicate downloads
  defaults/main.yml
  tasks/main.yml
Labels: enhancement

#11 :memo: Document SHA256 parameter in README
  README.md
Labels: bug, documentation

#12 :wrench: Adding platform info to Galaxy meta info
  meta/main.yml
Labels: enhancement
